In [4]:
from numpy import *
x = random.random((5,3))
print(x)

[[0.49273603 0.14585847 0.14499065]
 [0.91907914 0.44051432 0.11670967]
 [0.73961236 0.06101867 0.65615585]
 [0.06616893 0.75431053 0.3432359 ]
 [0.27226502 0.39882128 0.25546374]]


In [32]:
from numpy import *

lista_numeros_aleatorios_inteiros = random.randint(1, 30, 7)
lista_numeros_aleatorios_inteiros.sort()
print(lista_numeros_aleatorios_inteiros)

def amplitude (lista: list):
    minimo = min(lista)
    maximo = max(lista)
    print(f'A amplitude dessa lista vai de {minimo} até {maximo}')

amplitude(lista_numeros_aleatorios_inteiros)

[ 1 13 18 23 27 27 28]
A amplitude dessa lista vai de 1 até 28


In [34]:
def imprimeLetrasDaPalavra(palavra: string_) :
    for letra in palavra:
        print(letra)

imprimeLetrasDaPalavra("Python")

P
y
t
h
o
n


In [45]:
def precoPeloPesoCarga (peso: int):
    if peso <= 10:
        print(f"Peso da carga {peso} kg\n"
              "Valor: R$ 50,00")
    elif 11 <= peso <= 20 :
        print(f"Peso da carga {peso} kg\n"
              "Valor: R$ 80,00")
    elif peso <= 0:
        print("Peso inválido")
    else :
        print(f"Peso {peso} kg acima do aceitável para transporte.")
        
precoPeloPesoCarga(23)

Peso 23 kg acima do aceitável para transporte.
